services:
  - type: web
    name: poopers-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poopers-db
          property: connectionString
      - key: PORT
        value: 8000

  - type: web
    name: poopers-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerCommand: streamlit run home.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_URL
        value: https://poopers-backend.onrender.com
      - key: PORT
        value: 8501

databases:
  - name: poopers-db
    databaseName: poopers
    user: poopers
    plan: free 