name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      HF_USERNAME: IlVeZ
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      REPO_URL: https://huggingface.co/spaces/IlVeZ/poopers
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git
        run: |
          git config --global user.email "andreaverba@gmail.com" 
          git config --global user.name "IlVez23"  
      - name: Set Git Credentials
        run: |
          git config --global credential.helper store
          echo "https://${{ env.HF_USERNAME }}:${{ env.HF_TOKEN }}@huggingface.co" > ~/.git-credentials
      - name: Push to hub
        run: |
          # Clone the Hugging Face repository
          git clone "${{ env.REPO_URL }}" hf_repo
          cd hf_repo
          # Copy all files from the current directory to the Hugging Face repo
          cp -r ../* .
          cp -r ../.gitattributes .
          # Add and commit changes
          git add .
          git commit -m "Update from GitHub Actions"
          # Push to Hugging Face
          git push origin main